CREATE TABLE [dbo].[Category]
(
	ID INT NOT NULL IDENTITY
		CONSTRAINT [PK_dboCategory] PRIMARY KEY,

	[Name] VARCHAR(30) NOT NULL,
	[Description] VARCHAR(200),
	UsedGadget SMALLINT DEFAULT(0) NOT NULL
)
