CREATE TABLE [dbo].[Partitipation]
(
	ID INT NOT NULL
		CONSTRAINT [PK_dboParticipation] PRIMARY KEY IDENTITY,

	CompetitionID INT NOT NULL 
		CONSTRAINT [FK_dboParticipation_Competition] FOREIGN KEY
		REFERENCES Competition(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,

	UserID INT NOT NULL
		CONSTRAINT [FK_dboParticipation_User] FOREIGN KEY
		REFERENCES [User](ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,

	Score INT NOT NULL DEFAULT(0),

)
