CREATE TABLE [dbo].[Publisher]
(
	ID INT NOT NULL IDENTITY
		CONSTRAINT [PK_dboPublisher] PRIMARY KEY,

	CompetitionID INT NOT NULL
		CONSTRAINT [FK_dboPublisher_Competition] FOREIGN KEY
		REFERENCES Competition(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
		
	UserID INT
		CONSTRAINT [FK_dboPublisher_User] FOREIGN KEY
		REFERENCES [User](ID)
		ON UPDATE CASCADE
		ON DELETE SET NULL,
)
