CREATE TABLE [dbo].[User]
(
	ID INT NOT NULL IDENTITY,
	[Login] VARCHAR(50) NOT NULL
		CONSTRAINT UniqueLogin UNIQUE,

	Gender SMALLINT NOT NULL DEFAULT(0)
		CONSTRAINT GenderLimit CHECK(Gender >= 0 AND Gender <= 2),
	FirstName VARCHAR(30),
	LastName VARCHAR(30),
	Age SMALLINT NOT NULL
		CONSTRAINT NonNegativeAge CHECK(Age > 0),

	ShortDescription VARCHAR(200),
	RegistrationDate DATE NOT NULL DEFAULT GETDATE()

	CONSTRAINT [PK_dboUser] PRIMARY KEY ([ID])
)
